### ISSUE TITLE
Failed at building AOSP image for pdx237

### ISSUE THREAD

**Issue by alvkeke** [sonyxperiadev/device-sony-pdx237#1]
Hi,

I followed [the guide you provided](https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-13/) to build AOSP image, but failed with outputs below:

```log
device/sony/yodo/platform.mk was modified, regenerating...
device/sony/yodo/platform.mk was modified, regenerating...
[ 96% 1195/1233] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:57: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
system/sepolicy/Android.mk:62: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
FAILED: ninja: 'kernel/sony/msm-5.15/common-kernel/yodo/kernel', needed by 'out/target/product/pdx237/kernel', missing and no known rule to make it
22:31:33 ninja failed with: exit status 1

#### failed to build some targets (48 seconds) ####
```

I checked the [common-kernel](https://github.com/sonyxperiadev/kernel-sony-msm-5.15-common/tree/aosp/K.P.2.0.r1) repo, and found that there is no prebuilt kernel in that repo.

And I also found that there is no dts for pdx237 in [the kernel repo](https://github.com/sonyxperiadev/kernel/tree/aosp/K.P.2.0.r1).

Thanks

**Comment by jerpelea** [comment]
Xperia PDX237 is not a supported device yet!

Since all development is done in the open the basic code is there but the device lacks functionality.
Please wait for the official announcement for Xperia 1V and 5V

Best regards
Alin

**Comment by alvkeke** [comment]
Thanks for your reply!
How can I get the official announcement? Is there a specific website for that?

**Comment by jerpelea** [comment]
https://developer.sony.com/develop/open-devices/

**Comment by alvkeke** [comment]
thank you!
